# Generated by Django 3.2.13 on 2022-07-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Due_date', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
    ]
