# Generated by Django 3.2.13 on 2022-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeename', models.CharField(max_length=200)),
                ('Shift', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='addtaskmodel',
            name='Status',
            field=models.CharField(default='ToDo', max_length=200),
        ),
    ]
