# Generated by Django 3.2.13 on 2022-07-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODOAPP', '0002_auto_20220707_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeInformation',
            new_name='EmployeeInformationModel',
        ),
    ]
