# Generated by Django 3.2.13 on 2022-07-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODOAPP', '0003_rename_employeeinformation_employeeinformationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeInformationModel',
        ),
    ]
